{{- if .Values.wordpress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress-service
  labels:
    app: {{ .Release.Name }}-wordpress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: {{ .Release.Name }}-wordpress
{{- end }}
